name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ContinuousIntegration:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Unit Test
      run: ./gradlew clean test
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: build/test-results/**/*.xml
    - name: JaCoCo Report
      uses: Madrapps/jacoco-report@v1.1
      with:
        path: build/reports/jacoco/test/
        token: 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
    - name: Mutation Testing
      run: ./gradlew pitest
    - name: Build with Gradle
      run: ./gradlew build
